### PR TITLE
Update taxa_names.json to use common names in the dropdown menu.

### PR DESCRIPTION
**Pull request by SergePogorelov**

### CODE REVIEW

**Review by cheerstopaula — CHANGES_REQUESTED** [review]
I think this is a decision we should make as a team @angelazhu2 @oz03-hub. I personally think we should have the common name and in parenthesis and italic the binomial nomenclature. I don't really see the point in keeping the taxa ID (no one used it in the user studies, and if anything it can appear after the scientific name, in the parenthesis).

- Chilean flamingo (_Phoenicopterus chilensis_) or
- Chilean flamingo (_Phoenicopterus chilensis_, 4258) 

Common names are very English biased, so I don't think it is a good idea to keep that one exclusively.

**Comment by SergePogorelov** [comment]
> I think this is a decision we should make as a team @angelazhu2 @oz03-hub. I personally think we should have the common name and in parenthesis and italic the binomial nomenclature. I don't really see the point in keeping the taxa ID (no one used it in the user studies, and if anything it can appear after the scientific name, in the parenthesis).
> 
> * Chilean flamingo (_Phoenicopterus chilensis_) or
> * Chilean flamingo (_Phoenicopterus chilensis_, 4258)
> 
> Common names are very English biased, so I don't think it is a good idea to keep that one exclusively.

in the current implementation, the taxa_id is taken from the taxa name in order to make predictions or requests to the iNat API. 
I would not remove the taxa id from the name yet, otherwise the code will need to be changed and the tax ID stored somewhere.

**Comment by oz03-hub** [comment]
> Chilean flamingo (Phoenicopterus chilensis, 4258)

I prefer this one, and like sergei said we obtain taxa_id through slicing the strings, we need taxa for now in the name

**Comment by cheerstopaula** [comment]
> > Chilean flamingo (Phoenicopterus chilensis, 4258)
> 
> I prefer this one, and like sergei said we obtain taxa_id through slicing the strings, we need taxa for now in the name

Perfect!

**Review by ginic — APPROVED** [review]
This looks good to me! The formatting seems looks correct and will work with the code as is. Personally, the common names are easier to use, and I'm happy to merge this in unless people in the user study said they really like the scientific names.

**Comment by oz03-hub** [comment]
@SergePogorelov this can be merged or would you like to try `"common_name | scientific_name | (taxa)"`?

**Comment by SergePogorelov** [comment]
> @SergePogorelov this can be merged or would you like to try `"common_name | scientific_name | (taxa)"`?

here is `"common_name | scientific_name | (taxa)"`
in my opinion it is too long and does not even fit in the drop-down menu
image

**Comment by oz03-hub** [comment]
ok then, thanks for trying

**Review by cheerstopaula — APPROVED** [review]

**Pull request merged**
